index.html
Please do not consider the first two commits. One is a revert of the other. Sorry for the mess, won't happen often.
=> Querystring change + indentation suggestion

js/map.js
Some refactoring needed. Will do later.
=>  Flipping lat and lng for bounds passed to api.

css/style.css, css/w3.css, index.html, js/script.js
Made the drawer full bleed and smoothed up the transition a bit
=> In process stylings for the drawer

css/style.css, index.html
Added some polishing to the tree info text
=> styling the text

css/style.css, js/map.js
=> made the drawer and map transition nicer

js/map.js
* Fixes #22
* Zooms to a set of trees if there
is a token or organization parameter passed
=> Zoom to donor specific trees

server/server.js
Related issue: https://github.com/Greenstand/treetracker-web-map/issues/79
random screenshot for cluster results of `flavor = justdigit`
=> Add flavor to query

client/css/style.css, client/index.html, client/js/map.js
Related issue: https://github.com/Greenstand/treetracker-web-map/issues/45
=> Add map loader

client/js/map.js
Issue #117 - Formatted cluster text to decimal places. Ex: thousands indicate with a K , millions indicate with a M and so on.
=> Parse cluster text

client/css/style.css, client/index.html, client/js/map.js
Fixes #124 
* Map opens to full device width (bonus: zoom buttons and markers scale)
* "Powered by Greenstand" logo scales to device viewport appropriately
* Tree information panel scales appropriately on mobile devices
=> Mobile optimization

client/index.html, client/js/mapConfig.js, server/package-lock.json
Added script in index.html to access mapOptions. Widened bounds restriction by changing coordinates and changing zoom level to one higher to show all of Dar es Salaam.
=> Dar es saalam map

client/js/map.js, client/js/mapConfig.js
When the map loads it will be centered over dar es saalam
=> change map center to middle of dar

client/js/map.js
Attach zoomTarget to cluster marker if any, and jump to that target position when marker was clicked.
=> To resolve issue 160

client/src/map.js
Front end to handle map_name parameter
=> change organization to mapName

server/server.js
=> Added: map_name parameter in query, select from active_tree_region by the organization id/map_name

server/cron/assign-otp-india-certificate.js
Hope this is correct. Am so confused about the different branches.
=> Updated Planter IDs OTP

server/__tests__/integration.test.js, server/app.js, server/app.spec.js
Resolve #177 
Real demo:
In this case, userid/planter: 5127 has 5114 trees, so it will use the second query to get all the cluster, the speed is fast.
=> Solved issue177

server/app.js
Resolve #211 
Check the review comment below for details.
=> Fixed: zoom target is inacurate.

client/src/map.js
Here is the feature to pull the aerial imagery for Freetown as tiles from a server and overlay them onto the web map.
=> add freetown aerial image overlay

client/src/map.js
The newest version of master is broken, @Cl3arglass 's branch seems a bit problem, I have solved it.
=> Fixed: map is broken

client/src/map.js
=> side panel load on first render if query url treeid

client/src/components/Share.cy.js, client/src/components/Share.js
Resolved #227 
The effect of embedding the tree map to a HTML page.
=> Share tree with embed code.

client/src/components/SidePanel.cy.js, client/src/components/SidePanel.js
=> Fix bug/issue241

server/__tests__/integration.test.js, server/app.js, server/app.spec.js, server/models/Map.js, server/models/Map.spec.js, server/models/sqls/SQLCase1.js, server/models/sqls/SQLCase1V2.js, server/models/sqls/SQLCase2.js, server/models/sqls/SQLCase3.js, server/models/sqls/SQLCase4.js, server/models/sqls/SQLCase6.js, server/models/sqls/SQLZoomTargetCase1.js, server/models/sqls/SQLZoomTargetCase1V2.js
Resolve #234 
Resolve #225 
Use class/object to organize server code, make the code is better for understanding and maintaining.
Optimized the Freetown map.
Before optimization, on the dev env, Freetown map load took time 33923 ms,
After optimization, it took 2717 ms
=> Refactor server code structure; Optimize freetown map;

client/src/components/Share.js
=> Fixed: wrong name for twitter

client/src/map.js, client/src/mapConfig.js
=> add config file and settings for freetown

client/src/map.js
For issue 236 to solve the 403 errors from digital ocean
=> check if coord is in freetown tile range

client/cypress/integration/webMap.cy.js, client/package-lock.json, client/package.json, client/src/App.js, client/src/components/LoaderB.js, client/src/map.js
=> Show spin icon when loading slowly

client/package-lock.json, client/package.json, client/src/App.js, client/src/MapModel.js, client/src/map.js, client/src/mapTools.js, client/src/mapTools.test.js, client/src/style.css
* Replace google Maps with Leaflet.
* 100% replicated the older version without any change in terms of functionalities.
=> Switch to Leaflet

client/src/style.css
Added animation for control which is similar with GreenStand logo; Added common keyframes slideInFromBottom;
=> To resolve issue 296

client/src/map.js
Resolve #297 
Extend Leaflet method to allow manipulation of coordinate data;
Load Geo JSON data to draw Freetown overlay
Screenshot:
=> To resolve issue 297

client/src/map.js
* If it's case of wallet, userid, org, then use old way to render map.
* If not, use tile server to render tree point level.
=> Switch between new and old map mode.
